export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const ADD_SHIPPING = 'ADD_SHIPPING';


export const PRODUCTS_NAMES = {
    START_FETCH: "PRODUCTS_NAMES_START_FETCH",
    FAIL_FETCH: "PRODUCTS_NAMES_FAIL_FETCH",
    FINISH_FETCH: "PRODUCTS_NAMES_FINISH_FETCH"
};