# Generated by Django 3.1.4 on 2022-08-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20220827_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='date',
            new_name='date_time',
        ),
    ]
