# Generated by Django 3.1.4 on 2022-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20220829_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='wishlists',
            field=models.ManyToManyField(related_name='wishlists', to='shop.Wishlist'),
        ),
    ]
